### ISSUE TITLE
Type errors on GHC 8.8

### ISSUE THREAD

**Issue by fumieval** [jcpetruzza/barbies#16]
GHC 8.8 seem to infer quantifications differently from <8.6, resulting in type errors. I had to make the following changes to get this to compile:

https://github.com/haskell-vanguard/barbies/commit/a1d2d7d35296bcee36d8b9095ed07680b71de9bc

I haven't figured out how to make it work with 8.6 without resorting to CPP though.

**Comment by jcpetruzza** [comment]
@fumieval Thanks for submitting a fix! I managed to get it working without `CPP`.

**Comment by fumieval** [comment]
Nice
