### ISSUE TITLE
Template Haskell helper

### ISSUE THREAD

**Issue by fumieval** [jcpetruzza/barbies#24]
I made [barbies-th](https://github.com/fumieval/barbies-th), a wrapper library which generates strippable HKD from a normal definition.

```haskell
declareBareB [d|
  data Foo = Foo
    { foo :: Int
    , bar :: String
    }  |]
```

becomes

```haskell
data Foo sw h = Foo
    { foo :: Wear sw h Int,
    , bar :: Wear sw h String
    } deriving Generic
instance BareB Foo
instance FieldNamesB (Foo Covered) where
  bfieldNames = Foo (Const "foo") (Const "bar")
instance ProductB (Foo Covered) where
  bprod (Foo xfoo xbar) (Foo yfoo ybar)
    = Foo (Pair xfoo yfoo) (Pair xbar ybar)
instance FunctorB (Foo Covered)
instance TraversableB (Foo Covered)
instance ConstraintsB (Foo Covered)
instance ProductBC (Foo Covered)
```

Are you interested in introducing something like this to barbies? It does add template-haskell dependency, that's why I didn't go forward with a pull request.

**Comment by jcpetruzza** [comment]
Nice! I think a separate package for TH helpers as you've done is the right approach. There should probably be some a section in the `README` with pointers to related projects (there's also [higgledy](https://github.com/i-am-tom/higgledy)). If you have time to make a PR for that, I'd be happy to merge it.

**Comment by jcpetruzza** [comment]
I added a link to `barbies-th` from the README

**Comment by fumieval** [comment]
Oh thanks!
