### ISSUE TITLE
Typo in docs?

### ISSUE THREAD

**Issue by vagarenko** [jcpetruzza/barbies#52]
https://github.com/jcpetruzza/barbies/blob/daa82c8d42139f5fc23c01216741cff45a89b341/src/Barbies.hs#L168
says
`'tmap' :: 'FunctorT' t => (forall a. f a -> g a) -> t f x -> b g x`
shouldn't it be 
`'tmap' :: 'FunctorT' t => (forall a. f a -> g a) -> t f x -> t g x`
?
`t` not `b`

**Comment by jcpetruzza** [comment]
Thanks for reporting!
